substitutions:
  name: my-kitchen-ac
  friendly_name: Kitchen AC

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Must be used once. It is necessary to comment out after the first firmware update.
#  use_address: iot-uni-dongle.local

packages:
  default: github://dudanov/esphome-packages/hardware/iot-uni-dongle/device.yaml

external_components:
  - source: github://x15pa3ck15x/esphome_gree_hvac
    components: [ gree ]
    refresh: 0s

logger:
    level: INFO
    #level: DEBUG
    #level: VERY_VERBOSE
    #level: VERBOSE
    baud_rate: 0  

api:

ota:

web_server:
  port: 80

uart:
  # id: ac_uart
  tx_pin: 1
  rx_pin: 3
  baud_rate: 4800
  data_bits: 8
  parity: EVEN
  stop_bits: 1

climate:
  - platform: gree
    name: None
    # None only if you set "friendly_name" in substitutions
    # name: "Kitchen AC"
